[model_arguments]

[optimizer_arguments]
optimizer_type = "adafactor"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False" ]
lr_scheduler = "cosine_with_restarts"
# lr_warmup_steps = 500
lr_scheduler_num_cycles = 2
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"

[dataset_arguments]
train_data_dir=""
[training_arguments]
seed = 0
network_module = "networks.lora"
text_encoder_lr = 0.0004
unet_lr = 0.0004
network_dim = 256
cache_latents = true
no_half_vae = true
output_dir = "models"
# output_dir = "ComfyUI/models/checkpoints"
output_name = "phil_750_lr4e-4_cosine_restarts_2"
save_precision = "bf16"
train_batch_size = 1
max_train_steps = 750
gradient_checkpointing = true
# gradient_accumulation_steps = 1
mixed_precision = "bf16"
sample_prompts = "/workspace/sd-xl-experiments/lora/kohya_configs/prompts.txt"
log_with = "wandb"
xformers = true
# full_bf16 = true
[sample_prompt_arguments]
sample_every_n_steps = 250
sample_sampler = "k_dpm_2"

[saving_arguments]
save_model_as = "safetensors"
#save_last_n_steps = 500
#save_every_n_steps = 250
